import type { Career } from "@/types/game";

export type { Career } from "@/types/game";

export interface CareerInfo {
  id: Career;
  title: string;
  icon: string;
  description: string;
  salaryRange: string;
  medianSalary: string;
  skills: string[];
  overview: string;
  whatYouDo: string[];
  dayInLife: string[];
  pathToStart: string;
  certifications: string[];
  tools: string[];
  fastFacts: string[];
  gradient: string;
  backgroundImage: string;
}

export const careerInfoList: CareerInfo[] = [
  {
    id: "programmer",
    title: "Software Programmer",
    icon: "💻",
    description: "Write code, solve problems, and build digital solutions.",
    salaryRange: "$75,000 - $135,000",
    medianSalary: "$120,000",
    skills: ["JavaScript/TypeScript", "Debugging", "Algorithms", "Collaboration"],
    overview: "Software programmers turn ideas into digital tools used by people, teams, and businesses every day.",
    whatYouDo: [
      "Build and improve web apps, mobile apps, games, and internal tools.",
      "Break large problems into smaller steps that code can solve.",
      "Test features, fix bugs, and review code with teammates.",
      "Use APIs and databases to connect software to real-world data.",
    ],
    dayInLife: [
      "Review feature requests and choose the best technical approach.",
      "Write code for a new feature or bug fix.",
      "Run tests and use browser or server debugging tools.",
      "Explain your solution during a team review or demo.",
    ],
    pathToStart: "Start with programming fundamentals, build small projects, learn Git, and practice debugging real code.",
    certifications: ["AWS Certified Developer", "Microsoft Azure Fundamentals", "freeCodeCamp certifications"],
    tools: ["VS Code", "Git", "Browser DevTools", "APIs"],
    fastFacts: ["Often works on cross-functional teams", "Can specialize in front-end, back-end, games, or AI", "Strong logic and persistence matter more than memorizing syntax"],
    gradient: "from-blue-500 to-indigo-600",
    backgroundImage: "/images/programmer-bg.jpg",
  },
  {
    id: "nurse",
    title: "Registered Nurse",
    icon: "🏥",
    description: "Care for patients and make critical healthcare decisions.",
    salaryRange: "$65,000 - $115,000",
    medianSalary: "$86,000",
    skills: ["Patient Assessment", "Medication Safety", "Communication", "Triage"],
    overview: "Registered nurses combine science, empathy, and quick decision-making to help patients recover and stay safe.",
    whatYouDo: [
      "Assess symptoms, vital signs, and patient needs.",
      "Administer medication and monitor patient responses.",
      "Educate patients and families about care plans.",
      "Coordinate with doctors, technicians, and support staff.",
    ],
    dayInLife: [
      "Receive shift handoff and review patient assignments.",
      "Check vital signs and update care documentation.",
      "Respond to patient needs, medication schedules, and urgent changes.",
      "Communicate updates to the care team before shift end.",
    ],
    pathToStart: "Complete an approved nursing program, pass the NCLEX-RN, and build experience in clinical settings.",
    certifications: ["NCLEX-RN", "Basic Life Support", "Advanced Cardiovascular Life Support"],
    tools: ["Electronic Health Records", "Vital Signs Monitors", "Infusion Pumps", "Clinical Protocols"],
    fastFacts: ["Work can happen in hospitals, clinics, schools, or community care", "Prioritization is a daily skill", "Nurses advocate for patient safety and comfort"],
    gradient: "from-red-500 to-rose-600",
    backgroundImage: "/images/nurse-bg.jpg",
  },
  {
    id: "engineer",
    title: "Civil Engineer",
    icon: "🏗️",
    description: "Design structures and balance technical constraints.",
    salaryRange: "$70,000 - $125,000",
    medianSalary: "$95,000",
    skills: ["Structural Analysis", "Design Thinking", "Project Planning", "Safety Standards"],
    overview: "Civil engineers design and maintain infrastructure such as roads, bridges, water systems, and buildings.",
    whatYouDo: [
      "Analyze loads, materials, soil conditions, and environmental risks.",
      "Create designs that meet safety codes and budget limits.",
      "Review construction plans and inspect project progress.",
      "Use simulations and calculations to reduce failure risk.",
    ],
    dayInLife: [
      "Review project requirements and design constraints.",
      "Run calculations or simulations for a structure or system.",
      "Meet with architects, contractors, or city officials.",
      "Check plans for code compliance and safety concerns.",
    ],
    pathToStart: "Study engineering fundamentals, learn CAD and analysis tools, complete internships, and work toward licensure.",
    certifications: ["Fundamentals of Engineering", "Professional Engineer", "OSHA Safety Certification"],
    tools: ["AutoCAD", "Civil 3D", "Structural Analysis Software", "Surveying Equipment"],
    fastFacts: ["Projects can serve communities for decades", "Engineers balance safety, cost, and environmental impact", "Communication with non-engineers is essential"],
    gradient: "from-cyan-500 to-blue-600",
    backgroundImage: "/images/engineer-bg.jpg",
  },
  {
    id: "teacher",
    title: "Teacher",
    icon: "👩‍🏫",
    description: "Educate students and manage classroom dynamics.",
    salaryRange: "$50,000 - $90,000",
    medianSalary: "$65,000",
    skills: ["Communication", "Lesson Planning", "Classroom Management", "Empathy"],
    overview: "Teachers help learners build knowledge, confidence, and habits that support success inside and outside school.",
    whatYouDo: [
      "Plan lessons that match student needs and learning goals.",
      "Explain concepts in multiple ways until students understand.",
      "Assess progress and adjust instruction.",
      "Create a classroom environment where students feel respected.",
    ],
    dayInLife: [
      "Prepare materials and plan the day's learning activities.",
      "Teach lessons and check for understanding.",
      "Support students individually or in small groups.",
      "Grade work and plan next steps based on student progress.",
    ],
    pathToStart: "Earn a teaching degree or certification, complete student teaching, and keep building subject knowledge.",
    certifications: ["State Teaching License", "Special Education Endorsement", "National Board Certification"],
    tools: ["Learning Management Systems", "Assessment Rubrics", "Interactive Whiteboards", "Differentiated Materials"],
    fastFacts: ["Teachers adapt to many learning styles", "Patience and organization are daily requirements", "Good teaching combines content knowledge with relationship-building"],
    gradient: "from-indigo-400 to-blue-500",
    backgroundImage: "/images/teacher-bg.jpg",
  },
  {
    id: "chef",
    title: "Head Chef",
    icon: "👨‍🍳",
    description: "Create culinary experiences and manage kitchen operations.",
    salaryRange: "$45,000 - $85,000",
    medianSalary: "$58,000",
    skills: ["Menu Planning", "Food Safety", "Time Management", "Leadership"],
    overview: "Head chefs blend creativity, precision, and leadership to deliver consistent food and smooth kitchen operations.",
    whatYouDo: [
      "Plan menus, recipes, and food costs.",
      "Lead kitchen teams during busy service periods.",
      "Maintain food safety, quality, and presentation standards.",
      "Train cooks and solve problems quickly.",
    ],
    dayInLife: [
      "Review inventory and confirm ingredient quality.",
      "Prepare stations and assign tasks to the kitchen team.",
      "Guide service, taste dishes, and adjust timing.",
      "Review the shift and plan prep for the next day.",
    ],
    pathToStart: "Build cooking fundamentals, learn food safety, practice speed and consistency, and gain kitchen leadership experience.",
    certifications: ["ServSafe Food Protection Manager", "Culinary Arts Certificate", "HACCP Training"],
    tools: ["Chef Knives", "Mise en Place Systems", "Inventory Software", "Thermometers"],
    fastFacts: ["The role mixes creativity with strict safety rules", "Fast decisions matter during service", "Leadership and teamwork keep the kitchen moving"],
    gradient: "from-amber-500 to-orange-600",
    backgroundImage: "/images/chef-bg.jpg",
  },
  {
    id: "architect",
    title: "Architect",
    icon: "🏛️",
    description: "Design buildings that balance form, function, and safety.",
    salaryRange: "$70,000 - $120,000",
    medianSalary: "$90,000",
    skills: ["Spatial Thinking", "Design Systems", "Building Codes", "Client Communication"],
    overview: "Architects design spaces that are beautiful, functional, accessible, and safe for the people who use them.",
    whatYouDo: [
      "Translate client goals into sketches, plans, and models.",
      "Coordinate with engineers, contractors, and city reviewers.",
      "Select materials and systems that support the design.",
      "Check plans against building codes and accessibility standards.",
    ],
    dayInLife: [
      "Meet with clients to clarify goals and constraints.",
      "Develop drawings, 3D models, or material boards.",
      "Review structural, mechanical, and code requirements.",
      "Present design options and revise based on feedback.",
    ],
    pathToStart: "Study architecture, build a portfolio, complete required experience hours, and prepare for licensing exams.",
    certifications: ["ARE", "LEED Green Associate", "NCARB Certification"],
    tools: ["Revit", "AutoCAD", "SketchUp", "Building Code References"],
    fastFacts: ["Design decisions affect safety and accessibility", "Architecture blends art, science, and regulations", "Collaboration with engineers is constant"],
    gradient: "from-violet-500 to-purple-600",
    backgroundImage: "/images/architect-bg.jpg",
  },
  {
    id: "lawyer",
    title: "Lawyer",
    icon: "⚖️",
    description: "Analyze cases, apply legal reasoning, and advocate for clients.",
    salaryRange: "$70,000 - $180,000",
    medianSalary: "$135,000",
    skills: ["Legal Research", "Argument Writing", "Negotiation", "Ethical Reasoning"],
    overview: "Lawyers use research, writing, and advocacy to solve disputes, protect rights, and guide clients through rules.",
    whatYouDo: [
      "Research laws, precedents, and legal documents.",
      "Advise clients about risks, rights, and options.",
      "Draft contracts, motions, briefs, and agreements.",
      "Negotiate settlements or represent clients in hearings.",
    ],
    dayInLife: [
      "Review case files and identify key legal issues.",
      "Research statutes, regulations, and prior cases.",
      "Write arguments or prepare client communications.",
      "Negotiate, meet witnesses, or appear in court.",
    ],
    pathToStart: "Earn a law degree, pass the bar exam, complete ethics requirements, and build strong research and writing habits.",
    certifications: ["State Bar Admission", "Mediation Certification", "Specialized Practice Certifications"],
    tools: ["Legal Research Databases", "Case Management Software", "Briefs", "Evidence Rules"],
    fastFacts: ["Clear writing is as important as speaking", "Many lawyers spend more time researching than arguing", "Ethics and confidentiality guide every decision"],
    gradient: "from-blue-600 to-indigo-700",
    backgroundImage: "/images/lawyer-bg.jpg",
  },
  {
    id: "retail",
    title: "Retail Worker",
    icon: "🛍️",
    description: "Serve customers and manage store operations efficiently.",
    salaryRange: "$32,000 - $55,000",
    medianSalary: "$40,000",
    skills: ["Customer Service", "Sales", "Problem Solving", "Inventory Awareness"],
    overview: "Retail workers connect people with products, solve everyday problems, and keep stores running smoothly.",
    whatYouDo: [
      "Help customers find products and make informed choices.",
      "Handle transactions, returns, and service issues.",
      "Stock shelves, track inventory, and keep displays organized.",
      "Communicate with teammates and managers about store needs.",
    ],
    dayInLife: [
      "Open registers, review daily goals, and prepare the sales floor.",
      "Assist customers and answer product questions.",
      "Restock shelves and resolve checkout or return issues.",
      "Close the shift with cleaning, counts, and handoff notes.",
    ],
    pathToStart: "Build customer service, communication, and product knowledge through entry-level roles and cross-training.",
    certifications: ["Customer Service Certification", "POS System Training", "Loss Prevention Training"],
    tools: ["Point-of-Sale Systems", "Inventory Apps", "Product Displays", "Customer Service Scripts"],
    fastFacts: ["Retail builds communication and leadership skills", "Problem solving happens every shift", "Strong workers can move into management, buying, or operations"],
    gradient: "from-pink-500 to-rose-600",
    backgroundImage: "/images/retail-bg.jpg",
  },
  {
    id: "electrician",
    title: "Electrician",
    icon: "⚡",
    description: "Install and maintain electrical systems safely.",
    salaryRange: "$55,000 - $95,000",
    medianSalary: "$65,000",
    skills: ["Electrical Theory", "Blueprint Reading", "Safety Protocols", "Troubleshooting"],
    overview: "Electricians install, inspect, and repair electrical systems that power homes, businesses, and infrastructure.",
    whatYouDo: [
      "Read blueprints and follow electrical codes.",
      "Install wiring, panels, lighting, and control systems.",
      "Test circuits and troubleshoot faults safely.",
      "Maintain tools and follow lockout/tagout procedures.",
    ],
    dayInLife: [
      "Review job plans and confirm required materials.",
      "Install or repair wiring, fixtures, and panels.",
      "Test circuits and document completed work.",
      "Follow safety procedures before, during, and after the job.",
    ],
    pathToStart: "Enter an apprenticeship, learn code requirements, practice safe tool use, and work toward journeyman licensure.",
    certifications: ["Apprentice Electrician", "Journeyman Electrician License", "OSHA 10 or OSHA 30"],
    tools: ["Multimeters", "Wire Strippers", "Conduit Benders", "Circuit Testers"],
    fastFacts: ["Safety procedures are central to the job", "Work may be residential, commercial, or industrial", "Blueprint reading and code knowledge grow with experience"],
    gradient: "from-yellow-500 to-amber-600",
    backgroundImage: "/images/electrician-bg.jpg",
  },
];

export const careerInfoByCareer: Record<Career, CareerInfo> = {
  programmer: careerInfoList[0],
  nurse: careerInfoList[1],
  engineer: careerInfoList[2],
  teacher: careerInfoList[3],
  chef: careerInfoList[4],
  architect: careerInfoList[5],
  lawyer: careerInfoList[6],
  retail: careerInfoList[7],
  electrician: careerInfoList[8],
};
